repos:
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: python -m black
        types: [python]
        files: ^backend/

      - id: ruff
        name: ruff
        language: system
        entry: python -m ruff check --fix
        types: [python]
        files: ^backend/

      - id: ruff-format
        name: ruff-format
        language: system
        entry: python -m ruff format
        types: [python]
        files: ^backend/

      - id: mypy
        name: mypy
        language: system
        entry: python -m mypy
        args: [--config-file=backend/pyproject.toml, backend/app]
        pass_filenames: false
        files: ^backend/
